resolver: lts-15.1

allow-newer: true

packages:
- '.'

# Turn on system GHC
system-ghc: true
skip-ghc-check: true

dump-logs: all

build:
  keep-tmp-files: true
  cabal-verbose: true

extra-path:
  - /home/csaba/haskell/ghc-gitlab/bug-test/quickest/ghc/_build/stage1/bin
